//! SOE tool family (O3; `docs/soe-2026-10-08.md` § 13) — the weekly cycle's
//! stage tools over the private SOE state root
//! `<TENGU_HOME>/state/<sources.state>/` (critic C8, `outbound/soe/store.rs`).
//! The Architect reads its cycle and proposes; the Critic reads and
//! challenges. Every check and every id is the application's
//! (`application::soe::submit`); a tool never writes a file itself. Nothing
//! here contacts anyone, spends, publishes or deploys. One opt-in catalog row
//! per tool; interfaces live in [`defs`].
//!
//! | File | Tool |
//! |---|---|
//! | `view.rs` | `soe_view` — `soe_view/1:<run>:<view>`, read-only: the run's `head` (phase, limits, counts), its `packet` (the O2 evidence packet at the decision, paged, source text fenced), the week's `candidates` (new + carried, each with its inputs and bases), this run's `proposals` / `challenges`, and `history` (the `OpportunityEpisode`s of earlier cycles decided before this run — critic UNCOVERED 5) |
//! | `propose.rs` | `soe_propose` — one Architect draft through `submit::submit_proposal` (open run, `PROPOSE` phase, every check listed), stamped `<cycle>.pNN`; returns the id and a read-only preview (`rank::assess` of the draft under the run's profile at the decision: gates, rank keys) |
//! | `challenge.rs` | `soe_challenge` — one Critic draft, flat arguments, through `submit::submit_challenge` (`CHALLENGE` phase), stamped `<cycle>.cNN` |
//! | `tests.rs` | the tools inside a real `run_cycle` (in-memory and on-disk stores), the fixture state root `tests/fixtures/soe/state/` (regenerated by its test) |
//!
//! | Rule | Value |
//! |---|---|
//! | State root | `SandboxSections::sources_state_dir` (`[sources]`); none ⇒ every tool refuses `soe_state_missing`. `FsCycleStore` on it; nothing is created by a read |
//! | Run | the `run` argument = the goal's `run:` line (`cycles/<id>` · `replays/<id>`, `ports::soe::RunDir::parse`); a review dir or another text is refused |
//! | Scope | `fs_roots` = the workspace (`check_fs_write` / `check_fs_read` on it, as the xlab tools): the state root sits outside every fs root by design (load rule) — the tools' own state, never an agent path. No network, no env |
//! | Stage agent | the calling agent's name = `TENGU_AGENT_NAME` (a `run-agent` step; its bridge inherits it), else `TENGU_BRIDGE_AGENT`, read once when the plugin is built; a write with none is refused (`stage_agent_unknown`). With `[soe]`: `soe_propose` only as `soe.architect`, `soe_challenge` only as `soe.critic` (`stage_agent_mismatch`) |
//! | Provenance ([`Stamp::provenance`]) | `agent` (above) · `model` / `engine` (the agent's block) · `skill_sha256` = the step's own (`runner::SKILL_SHA256_ENV`, exported by `run-agent` from the cwd the stage cache key sees — a Claude Code bridge runs in the workspace and inherits it), else `runner::skill_sha256_of` over the agent's skill packages (its `workspace`, else the tool's) — the stage cache key's own identity · `generation` = the bound `[generation]` id, else `UNBOUND` (`submit::UNBOUND`; the cycle refuses another, `generation_mismatch`) · `call_id` (`UNKNOWN` without one) · `proposed_at` = now |
//! | Refusals | `submit_*`'s codes, one line each (`stage_closed`, `computed_field`, `unsupported_evidence`, `duplicate`, …) — the tool errors; nothing is written |
//! | Text | ≤ [`TEXT_BUDGET`] bytes (a 16k local model's result cap); ids and hashes in full; model and source text only inside a `source-text` fence after one note |

pub(crate) mod challenge;
pub(crate) mod defs;
pub(crate) mod propose;
pub(crate) mod view;

#[cfg(test)]
mod tests;

use std::path::Path;
use std::sync::Arc;

use anyhow::{anyhow, bail, Result};
use async_trait::async_trait;
use serde_json::{Map, Value};

use crate::adapters::outbound::clock::SystemClock;
use crate::adapters::outbound::soe::runner::{skill_sha256_of, SKILL_SHA256_ENV};
use crate::adapters::outbound::soe::store::FsCycleStore;
use crate::adapters::outbound::tools::xlab::{field, object_args, opt_str};
use crate::application::soe::submit::UNBOUND;
use crate::config::paths::expand_tilde;
use crate::config::sections::SandboxSections;
use crate::config::AgentConfig;
use crate::domain::lineage::value::Time;
use crate::domain::soe::proposal::Provenance;
use crate::domain::soe::value::ValueError;
use crate::ports::clock::Clock;
use crate::ports::soe::{CycleStore, RunDir};
use crate::ports::tool::{PluginCtx, Tool, ToolPlugin};

pub(crate) use defs::defs_named;

/// Refusal without `[sources]` (module table: state root).
pub(crate) const SOE_STATE_MISSING: &str = "soe_state_missing";
/// A write by an agent whose name no env names (module table).
pub(crate) const STAGE_AGENT_UNKNOWN: &str = "stage_agent_unknown";
/// A write by an agent that is not the `[soe]` stage's.
pub(crate) const STAGE_AGENT_MISMATCH: &str = "stage_agent_mismatch";
/// Largest text a tool returns, in bytes: ≤ 3/4 of a 16k-window local
/// model's 8 192-char result cap (`engines/local.rs`), as the xlab and source
/// tools keep.
pub(crate) const TEXT_BUDGET: usize = 6_000;

/// Who calls, as the stamp needs it (module table: stage agent, provenance).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Stamp {
    /// The calling agent's name; `None` = no env names it.
    pub agent: Option<String>,
    pub model: String,
    pub engine: String,
    /// The agent's skill packages, for `skill_sha256`.
    pub skill_packages: Vec<String>,
    /// Where its skills are found (`runner::skill_sha256`).
    pub workspace: std::path::PathBuf,
    /// The step's own skill identity (`runner::SKILL_SHA256_ENV`, exported
    /// by `run-agent`); `None` = computed from `skill_packages` here.
    pub step_skill_sha256: Option<String>,
    /// `[generation] id`, else `UNBOUND`.
    pub generation: String,
}

impl Stamp {
    /// The stamp of the agent a plugin is built for (module table).
    fn of(config: &AgentConfig, workspace: &Path, agent: Option<String>) -> Self {
        Stamp {
            agent,
            step_skill_sha256: std::env::var(SKILL_SHA256_ENV)
                .ok()
                .filter(|s| crate::domain::evidence::valid_sha256(s)),
            model: config.model.clone(),
            engine: config.engine.clone(),
            skill_packages: config.skill_packages.clone(),
            workspace: config
                .workspace
                .as_deref()
                .map(expand_tilde)
                .unwrap_or_else(|| workspace.to_path_buf()),
            generation: config
                .sandbox
                .generation
                .as_ref()
                .map_or_else(|| UNBOUND.to_string(), |g| g.id.clone()),
        }
    }

    /// The stage agent's name, or the refusal; with `[soe]`, it must be
    /// `want` (`soe.architect` / `soe.critic`).
    pub(crate) fn check_agent(&self, tool: &str, want: Option<&str>) -> Result<&str> {
        let Some(name) = self.agent.as_deref() else {
            bail!(
                "{STAGE_AGENT_UNKNOWN}: {tool} writes from a stage run — no TENGU_AGENT_NAME (a \
                 `run-agent` step sets it) and no TENGU_BRIDGE_AGENT name the calling agent"
            );
        };
        if let Some(want) = want.filter(|w| *w != name) {
            bail!(
                "{STAGE_AGENT_MISMATCH}: {tool} is the stage tool of [agents.{want}] ([soe]); \
                 `{name}` called it"
            );
        }
        Ok(name)
    }

    /// The provenance of one write by `agent` (module table).
    pub(crate) fn provenance(&self, agent: &str, call_id: Option<&str>, now_ms: i64) -> Provenance {
        Provenance {
            agent: agent.to_string(),
            model: self.model.clone(),
            engine: self.engine.clone(),
            skill_sha256: self
                .step_skill_sha256
                .clone()
                .unwrap_or_else(|| skill_sha256_of(&self.skill_packages, &self.workspace)),
            generation: self.generation.clone(),
            call_id: call_id
                .filter(|c| !c.trim().is_empty())
                .unwrap_or("UNKNOWN")
                .to_string(),
            proposed_at: Time::At(now_ms),
        }
    }
}

/// Handles every family tool shares.
#[derive(Clone)]
pub(crate) struct SoeShared {
    /// The cycle store on the state root, or the refusal (module table).
    pub store: Result<Arc<dyn CycleStore>, String>,
    /// The sandbox's sections (`[soe]`, `[generation]`).
    pub sandbox: Arc<SandboxSections>,
    pub clock: Arc<dyn Clock>,
    pub stamp: Stamp,
}

impl SoeShared {
    pub(crate) fn store(&self) -> Result<&dyn CycleStore> {
        match &self.store {
            Ok(s) => Ok(s.as_ref()),
            Err(why) => Err(anyhow!("{why}")),
        }
    }
}

/// The state root's store of `sections`, or the refusal (module table).
pub(crate) fn open_store(sections: &SandboxSections) -> Result<Arc<dyn CycleStore>, String> {
    sections
        .sources_state_dir
        .as_ref()
        .map(|root| Arc::new(FsCycleStore::new(root)) as Arc<dyn CycleStore>)
        .ok_or_else(|| {
            format!(
                "{SOE_STATE_MISSING}: no [sources] section — the SOE state root (cycles, replays, \
                 logs) is <TENGU_HOME>/state/<sources.state>/; add [sources] state = \"<name>\""
            )
        })
}

/// The calling agent's name from the env (module table: stage agent).
fn agent_from_env() -> Option<String> {
    ["TENGU_AGENT_NAME", "TENGU_BRIDGE_AGENT"]
        .iter()
        .filter_map(|k| std::env::var(k).ok())
        .map(|v| v.trim().to_string())
        .find(|v| !v.is_empty())
}

// ── Arguments ──────────────────────────────────────────────────────

/// The `run` argument as a cycle or replay dir (module table: run).
pub(crate) fn run_arg(tool: &str, o: &Map<String, Value>) -> Result<RunDir> {
    let text = opt_str(tool, o, "run")?.ok_or_else(|| {
        anyhow!("{tool}: 'run' is required — the run dir your goal names (`run: cycles/<id>`)")
    })?;
    match RunDir::parse(text) {
        Some(d @ (RunDir::Cycle(_) | RunDir::Replay(_))) => Ok(d),
        _ => bail!(
            "{tool}: 'run' `{text}` is no run dir — give the goal's `run:` value, `cycles/<id>` \
             or `replays/<id>`"
        ),
    }
}

/// Strict object arguments (an unknown key is an error).
pub(crate) fn args<'a>(
    tool: &str,
    args: &'a Value,
    allowed: &[&str],
) -> Result<&'a Map<String, Value>> {
    object_args(tool, args, allowed)
}

/// An optional array of non-empty strings.
pub(crate) fn opt_strings(tool: &str, o: &Map<String, Value>, key: &str) -> Result<Vec<String>> {
    match field(o, key) {
        None => Ok(Vec::new()),
        Some(Value::Array(a)) => a
            .iter()
            .map(|v| match v.as_str().map(str::trim) {
                Some(s) if !s.is_empty() => Ok(s.to_string()),
                _ => bail!("{tool}: '{key}' must be an array of non-empty strings, got {v}"),
            })
            .collect(),
        Some(v) => bail!("{tool}: '{key}' must be an array of strings, got {v}"),
    }
}

/// `submit_*`'s refusal as the tool's error: every problem, one line each.
pub(crate) fn refused(tool: &str, run: &RunDir, errors: &[ValueError]) -> anyhow::Error {
    let lines: Vec<String> = errors.iter().map(|e| format!("- {e}")).collect();
    anyhow!(
        "{tool}: {run} refused the draft ({} problem(s); nothing was written):\n{}",
        errors.len(),
        lines.join("\n")
    )
}

/// Plugin grouping the SOE tools; each catalog row shares it.
pub(crate) struct SoePlugin;

#[async_trait]
impl ToolPlugin for SoePlugin {
    fn name(&self) -> &'static str {
        "soe"
    }

    async fn tools(&self, ctx: &PluginCtx<'_>) -> Result<Vec<Arc<dyn Tool>>> {
        let sections = &ctx.config.sandbox;
        let shared = SoeShared {
            store: open_store(sections),
            sandbox: Arc::clone(sections),
            clock: Arc::new(SystemClock),
            stamp: Stamp::of(ctx.config, ctx.workspace, agent_from_env()),
        };
        Ok(tools(&shared))
    }
}

/// The family's tools over `shared`.
pub(crate) fn tools(shared: &SoeShared) -> Vec<Arc<dyn Tool>> {
    vec![
        Arc::new(view::SoeViewTool::new(shared.clone())),
        Arc::new(propose::SoeProposeTool::new(shared.clone())),
        Arc::new(challenge::SoeChallengeTool::new(shared.clone())),
    ]
}
