//! Anthropic Messages API backend implementation.
//!
//! Potential use case:
//! Route runtime turns to hosted Claude models through a typed REST contract.

use async_trait::async_trait;
use futures::stream;
use futures::Stream;
use serde::{Deserialize, Serialize};
use std::pin::Pin;
use tracing::{debug, error};

use tengu_core::types::message::Role;
use tengu_core::types::{Message, ModelInfo, StreamEvent, ToolDef};
use tengu_core::{Engine, EngineContext, EngineDiagnostics};

/// Engine implementation backed by Anthropic Messages API.
pub struct AnthropicEngine {
    base_url: String,
    model: String,
    api_key: String,
    client: reqwest::Client,
}

#[derive(Debug, Serialize)]
struct AnthropicMessagesRequest {
    /// Anthropic model identifier (for example: `claude-3-5-sonnet-latest`).
    model: String,
    /// Maximum response tokens for this turn.
    max_tokens: u32,
    /// Typed conversation history.
    messages: Vec<AnthropicInputMessage>,
    /// Enable SSE streaming mode.
    stream: bool,
    /// Optional system prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    system: Option<String>,
}

#[derive(Debug, Serialize)]
struct AnthropicInputMessage {
    /// Anthropic role label (`user` or `assistant`).
    role: String,
    /// Message content blocks.
    content: Vec<AnthropicTextBlock>,
}

#[derive(Debug, Serialize, Deserialize)]
struct AnthropicTextBlock {
    /// Anthropic content block type (we currently use `text` only).
    #[serde(rename = "type")]
    kind: String,
    /// Text content payload.
    text: String,
}

#[derive(Debug, Deserialize)]
struct AnthropicMessagesResponse {
    /// Output content blocks generated by Anthropic.
    #[serde(default)]
    content: Vec<AnthropicOutputBlock>,
    /// Usage counters for the completed response.
    #[serde(default)]
    usage: Option<AnthropicUsage>,
}

#[derive(Debug, Deserialize)]
struct AnthropicOutputBlock {
    /// Block type.
    #[serde(rename = "type")]
    kind: String,
    /// Optional text value for text blocks.
    #[serde(default)]
    text: Option<String>,
}

#[derive(Debug, Deserialize)]
struct AnthropicUsage {
    /// Prompt token count for this response.
    #[serde(default)]
    input_tokens: u32,
    /// Generated token count for this response.
    #[serde(default)]
    output_tokens: u32,
}

impl AnthropicEngine {
    /// Create a new Anthropic engine using API endpoint, model, and API key.
    pub fn new(base_url: &str, model: &str, api_key: &str) -> Self {
        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            model: model.to_string(),
            api_key: api_key.to_string(),
            client: reqwest::Client::new(),
        }
    }

    /// Convert core messages into Anthropic `user`/`assistant` chat turns.
    fn convert_messages(messages: &[Message]) -> Vec<AnthropicInputMessage> {
        messages
            .iter()
            .filter(|m| !matches!(m.role, Role::System))
            .map(|m| {
                let role = match m.role {
                    Role::Assistant => "assistant",
                    Role::User | Role::Tool | Role::System => "user",
                };
                AnthropicInputMessage {
                    role: role.to_string(),
                    content: vec![AnthropicTextBlock {
                        kind: "text".to_string(),
                        text: m.content.clone(),
                    }],
                }
            })
            .collect()
    }

    /// Extract concatenated text response from typed Anthropic blocks.
    fn extract_text(response: &AnthropicMessagesResponse) -> String {
        response
            .content
            .iter()
            .filter(|block| block.kind == "text")
            .filter_map(|block| block.text.as_deref())
            .collect::<Vec<_>>()
            .join("")
    }

    /// Build terminal success events in deterministic order.
    fn success_events(response: &AnthropicMessagesResponse) -> Vec<StreamEvent> {
        let mut events = Vec::new();
        let text = Self::extract_text(response);
        if !text.is_empty() {
            events.push(StreamEvent::TextDelta { text });
        }
        if let Some(usage) = &response.usage {
            events.push(StreamEvent::Usage {
                input_tokens: usage.input_tokens,
                output_tokens: usage.output_tokens,
            });
        }
        events.push(StreamEvent::Done);
        events
    }
}

#[async_trait]
impl Engine for AnthropicEngine {
    fn id(&self) -> &str {
        "anthropic"
    }

    fn context_window(&self) -> usize {
        200_000
    }

    fn supports_tool_use(&self) -> bool {
        false
    }

    fn manages_own_workspace(&self) -> bool {
        false
    }

    fn supports_streaming(&self) -> bool {
        false
    }

    fn diagnostics(&self) -> EngineDiagnostics {
        EngineDiagnostics {
            engine_id: self.id().to_string(),
            configured_model: Some(self.model.clone()),
            endpoint: Some(self.base_url.clone()),
            transport: Some("http-json".to_string()),
            capabilities: self.capabilities(),
        }
    }

    fn available_models(&self) -> Vec<ModelInfo> {
        vec![ModelInfo {
            id: self.model.clone(),
            provider: "anthropic".to_string(),
            display_name: self.model.clone(),
            context_window: self.context_window(),
            supports_tools: self.supports_tool_use(),
            supports_streaming: self.supports_streaming(),
        }]
    }

    async fn run(
        &self,
        messages: &[Message],
        _tools: &[ToolDef],
        context: &EngineContext,
    ) -> anyhow::Result<Pin<Box<dyn Stream<Item = StreamEvent> + Send>>> {
        let request = AnthropicMessagesRequest {
            model: self.model.clone(),
            max_tokens: 1_024,
            messages: Self::convert_messages(messages),
            stream: false,
            system: context.system_prompt.clone(),
        };

        if request.messages.is_empty() {
            return Ok(Box::pin(stream::iter(vec![StreamEvent::Error {
                message: "Anthropic request has no user/assistant messages".to_string(),
            }])));
        }

        debug!(model = %self.model, "Sending request to Anthropic");

        let response = self
            .client
            .post(format!("{}/v1/messages", self.base_url))
            .header("x-api-key", &self.api_key)
            .header("anthropic-version", "2023-06-01")
            .json(&request)
            .send()
            .await?;

        if !response.status().is_success() {
            let status = response.status();
            let body = response.text().await.unwrap_or_default();
            error!(%status, %body, "Anthropic request failed");
            return Ok(Box::pin(stream::iter(vec![StreamEvent::Error {
                message: format!("Anthropic error {}: {}", status, body),
            }])));
        }

        let parsed: AnthropicMessagesResponse = response.json().await?;
        Ok(Box::pin(stream::iter(Self::success_events(&parsed))))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn msg(role: Role, content: &str) -> Message {
        Message {
            role,
            content: content.to_string(),
            tool_call_id: None,
            tool_calls: None,
        }
    }

    #[test]
    fn convert_messages_skips_system_and_maps_roles() {
        let converted = AnthropicEngine::convert_messages(&[
            msg(Role::System, "sys"),
            msg(Role::User, "u"),
            msg(Role::Assistant, "a"),
            msg(Role::Tool, "t"),
        ]);

        assert_eq!(converted.len(), 3);
        assert_eq!(converted[0].role, "user");
        assert_eq!(converted[1].role, "assistant");
        assert_eq!(converted[2].role, "user");
    }

    #[test]
    fn success_events_order_text_usage_done() {
        let response = AnthropicMessagesResponse {
            content: vec![AnthropicOutputBlock {
                kind: "text".to_string(),
                text: Some("hello".to_string()),
            }],
            usage: Some(AnthropicUsage {
                input_tokens: 12,
                output_tokens: 7,
            }),
        };

        let events = AnthropicEngine::success_events(&response);
        assert_eq!(events.len(), 3);
        assert!(matches!(events[0], StreamEvent::TextDelta { ref text } if text == "hello"));
        assert!(matches!(
            events[1],
            StreamEvent::Usage {
                input_tokens: 12,
                output_tokens: 7
            }
        ));
        assert!(matches!(events[2], StreamEvent::Done));
    }

    #[test]
    fn diagnostics_report_endpoint_model_and_transport() {
        let engine = AnthropicEngine::new(
            "https://api.anthropic.com/",
            "claude-3-5-sonnet-latest",
            "test-key",
        );
        let diagnostics = engine.diagnostics();

        assert_eq!(diagnostics.engine_id, "anthropic");
        assert_eq!(
            diagnostics.configured_model.as_deref(),
            Some("claude-3-5-sonnet-latest")
        );
        assert_eq!(
            diagnostics.endpoint.as_deref(),
            Some("https://api.anthropic.com")
        );
        assert_eq!(diagnostics.transport.as_deref(), Some("http-json"));
    }
}
